# Generated by Django 4.2.4 on 2023-08-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, unique=True, verbose_name='Телефонный номер')),
                ('invite_code', models.CharField(max_length=6, unique=True, verbose_name='Код для приглашений')),
                ('referal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to='users.user')),
            ],
            options={
                'ordering': ('-phone_number',),
            },
        ),
    ]
